services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: audico_ai_db
      POSTGRES_USER: audico_admin
      POSTGRES_PASSWORD: AudicoAI2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://audico_admin:AudicoAI2024!@db:5432/audico_ai_db
      - REDIS_URL=redis://redis:6379
      - CHROMA_URL=http://chromadb:8000
    depends_on:
      - db
      - redis
      - chromadb
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
  chromadb_data:
